# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b376dcdf1bdbee30ce7dde6270f95a8b6ff5bdbcb98a6942125b90fb6000c7f3d4c91ec3f20af8d90a046c803607f864bdc19bd6ba4f3368f4fb9f12c7cbc9a

test:
  secret_key_base: 3d6e787990f960cb84fb40a9b817e9df0a85ffc95c2539a7dc47470359329fbcd7a9aa9278102c70e0a7a8ae429c32225b2964a84709a454cb9791f0644798b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
